# Check BLAS installation
FIND_LIBRARY(BLAS_FOUND_LIBRARY NAMES blas
  HINTS ${BLAS_INSTALL_PATH}/lib ${BLAS_INSTALL_PATH}/lib64
)

IF (BLAS_FOUND_LIBRARY)
  ADD_LIBRARY(blas INTERFACE)
  SET_TARGET_PROPERTIES(blas PROPERTIES
    INTERFACE_LINK_LIBRARIES ${BLAS_FOUND_LIBRARY}
  )
  SET(BLAS_FOUND ON)
  INSTALL(TARGETS blas
    EXPORT tacho-targets
    LIBRARY DESTINATION "${TACHO_INSTALL_LIB_PATH}"
    ARCHIVE DESTINATION "${TACHO_INSTALL_LIB_PATH}"
  )
  MESSAGE("-- BLAS is found at ${BLAS_FOUND_LIBRARY}")
ENDIF()

