# Check LAPACK installation
FIND_LIBRARY(LAPACK_FOUND_LIBRARY NAMES lapack
  HINTS ${LAPACK_INSTALL_PATH}/lib ${LAPACK_INSTALL_PATH}/lib64
)

IF (LAPACK_FOUND_LIBRARY)
  ADD_LIBRARY(lapack INTERFACE)
  SET_TARGET_PROPERTIES(lapack PROPERTIES
    INTERFACE_LINK_LIBRARIES ${LAPACK_FOUND_LIBRARY}
  )
  SET(LAPACK_FOUND ON)
  INSTALL(TARGETS lapack
    EXPORT tacho-targets
    LIBRARY DESTINATION "${TACHO_INSTALL_LIB_PATH}"
    ARCHIVE DESTINATION "${TACHO_INSTALL_LIB_PATH}"
  )
  MESSAGE("-- LAPACK is found at ${LAPACK_FOUND_LIBRARY}")
ENDIF()

